## 
## Cadence First Encounter "v08.10-p004_1 ((32bit) 11/04/2008 14:34 (Linux 2.6))"
## Mon Aug 26 19:43:21 2024
## 
set sdc_version 1.4
current_design SYS_TOP
create_clock [get_ports {UART_CLK}]  -name UART_CLK -period 271.297 -waveform {0 135.648}
create_clock [get_ports {REF_CLK}]  -name REF_CLK -period 20 -waveform {0 10}
create_clock [get_ports {scan_clk}]  -name SCAN_CLK -period 100 -waveform {0 50}
create_generated_clock -name ALU_CLK -source [get_ports {REF_CLK}] -divide_by 1 -master_clock [get_clocks {REF_CLK}] -add [get_pins {CLK_GATE/U0_TLATNCAX12M/ECK}]
create_generated_clock -name RX_CLK -source [get_ports {UART_CLK}] -divide_by 1 -master_clock [get_clocks {UART_CLK}] -add [get_pins {CLK_DIV_1/U38/Y}]
create_generated_clock -name TX_CLK -source [get_ports {UART_CLK}] -divide_by 32 -master_clock [get_clocks {UART_CLK}] -add [get_pins {CLK_DIV_2/U38/Y}]
set_propagated_clock  [get_pins {CLK_DIV_2/U38/Y}]
set_propagated_clock  [get_pins {CLK_GATE/U0_TLATNCAX12M/ECK}]
set_propagated_clock  [get_ports {UART_CLK}]
set_propagated_clock  [get_ports {scan_clk}]
set_propagated_clock  [get_pins {CLK_DIV_1/U38/Y}]
set_propagated_clock  [get_ports {REF_CLK}]
set_clock_latency -min 0 [get_clocks {ALU_CLK}]
set_clock_latency -max 0 [get_clocks {ALU_CLK}]
set_clock_latency -min 0 [get_clocks {TX_CLK}]
set_clock_latency -max 0 [get_clocks {TX_CLK}]
set_clock_latency -min 0 [get_clocks {RX_CLK}]
set_clock_latency -max 0 [get_clocks {RX_CLK}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[0]}]
set_load -pin_load -max  0.1  [get_ports {SO[3]}]
set_load -pin_load -min  0.1  [get_ports {SO[3]}]
set_load -pin_load -max  0.1  [get_ports {SO[2]}]
set_load -pin_load -min  0.1  [get_ports {SO[2]}]
set_load -pin_load -max  0.1  [get_ports {SO[1]}]
set_load -pin_load -min  0.1  [get_ports {SO[1]}]
set_load -pin_load -max  0.1  [get_ports {SO[0]}]
set_load -pin_load -min  0.1  [get_ports {SO[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {RX_IN}]
set_load -pin_load -max  0.1  [get_ports {TX_OUT}]
set_load -pin_load -min  0.1  [get_ports {TX_OUT}]
set_load -pin_load -max  0.1  [get_ports {PARITY_ERROR}]
set_load -pin_load -min  0.1  [get_ports {PARITY_ERROR}]
set_load -pin_load -max  0.1  [get_ports {STOP_ERROR}]
set_load -pin_load -min  0.1  [get_ports {STOP_ERROR}]
set_load -pin_load -max  0.1  [get_ports {BUSY}]
set_load -pin_load -min  0.1  [get_ports {BUSY}]
set_case_analysis 1 [get_ports {test_mode}]
set_input_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SE}]
set_input_delay -add_delay 54.2594 -clock [get_clocks {UART_CLK}] [get_ports {RX_IN}]
set_input_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {test_mode}]
set_input_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SI[2]}]
set_input_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SI[0]}]
set_input_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SI[3]}]
set_input_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SI[1]}]
set_output_delay -add_delay 54.2594 -clock [get_clocks {UART_CLK}] [get_ports {PARITY_ERROR}]
set_output_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SO[0]}]
set_output_delay -add_delay 54.2594 -clock [get_clocks {UART_CLK}] [get_ports {STOP_ERROR}]
set_output_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SO[3]}]
set_output_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SO[1]}]
set_output_delay -add_delay 54.2594 -clock [get_clocks {UART_CLK}] [get_ports {TX_OUT}]
set_output_delay -add_delay 54.2594 -clock [get_clocks {UART_CLK}] [get_ports {BUSY}]
set_output_delay -add_delay 20 -clock [get_clocks {SCAN_CLK}] [get_ports {SO[2]}]
set_clock_uncertainty 0.1 -hold [get_clocks {ALU_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {ALU_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {TX_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {TX_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {RX_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {RX_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {SCAN_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {SCAN_CLK}]
set_clock_uncertainty -hold   0.1 [get_ports {UART_CLK}]
set_clock_uncertainty -setup   0.2 [get_ports {UART_CLK}]
set_clock_uncertainty -hold   0.1 [get_ports {REF_CLK}]
set_clock_uncertainty -setup   0.2 [get_ports {REF_CLK}]
set_clock_groups -name REF_CLK_1 -asynchronous  -group  [get_clocks {ALU_CLK REF_CLK}] -group  [get_clocks {TX_CLK RX_CLK UART_CLK}] -group  [get_clocks {SCAN_CLK}]
